import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import postcss from 'postcss'
import tailwindcss from 'tailwindcss'
import { describe, expect, it } from 'vitest'
import {
  FIXTURE_PATH,
  OUTPUT_PATH,
  channels,
  cssVar,
  generateTokensCss,
  isRawRole,
  loadTokens,
  motionVars,
  radiusRoles,
  springCurve,
  springPosition,
  tailwindTheme,
  typeRoles,
} from '../../../../scripts/gen-tokens.mjs'

const root = resolve(__dirname, '..', '..', '..', '..')
const lf = (text: string) => text.replace(/\r\n?/g, '\n')
const tokens = loadTokens()
const roleNames = Object.keys(tokens.roles)

/** The declarations of the first rule block that starts with `selector` in a stylesheet. */
function block(css: string, selector: string): string {
  const start = css.indexOf(`\n${selector} {`)
  if (start < 0) throw new Error(`no ${selector} block`)
  return css.slice(start, css.indexOf('\n}', start))
}

describe('the token file', () => {
  it('is contract version 1 with a light and a dark #RRGGBB value for every role', () => {
    expect(tokens.contractVersion).toBe(1)
    expect(roleNames.length).toBeGreaterThan(20)
    for (const role of roleNames) {
      expect(tokens.roles[role].light, `${role} light`).toMatch(/^#[0-9A-F]{6}$/)
      expect(tokens.roles[role].dark, `${role} dark`).toMatch(/^#[0-9A-F]{6}$/)
    }
  })

  it('lists aliases and raw roles that are roles, with one CSS variable per role', () => {
    for (const role of Object.keys(tokens.css.aliases)) expect(roleNames, role).toContain(role)
    for (const role of tokens.css.rawVar) expect(roleNames, role).toContain(role)
    const names = roleNames.map((role) => cssVar(tokens, role))
    expect(new Set(names).size).toBe(names.length)
    for (const name of names) expect(name).toMatch(/^--[a-z]+(-[a-z]+)*$/)
  })

  it('keeps every contrast rule on roles of the file', () => {
    for (const rule of tokens.contrast.rules) {
      expect(roleNames, rule.name).toContain(rule.fg)
      for (const bg of rule.bg) {
        if (typeof bg === 'string') expect(roleNames, rule.name).toContain(bg)
        else {
          expect(roleNames, rule.name).toContain(bg.tint)
          expect(roleNames, rule.name).toContain(bg.over)
        }
      }
    }
  })

  it('has no type below 11 px, a radius or a duration that is not a number', () => {
    const roles = typeRoles(tokens)
    expect(Object.keys(roles)).toEqual(['page-title', 'section', 'group', 'task-title', 'card-title', 'meta', 'chip', 'caption'])
    for (const [name, t] of Object.entries(roles)) expect(t.size, name).toBeGreaterThanOrEqual(11)
    expect(radiusRoles(tokens)).toEqual({ control: '6px', popover: '10px', card: '12px', chip: '9999px' })
    for (const [name, value] of motionVars(tokens)) {
      if (name.startsWith('--dur-')) expect(value, name).toMatch(/^\d+ms$/)
    }
  })
})

describe('tokens.css', () => {
  const css = lf(readFileSync(OUTPUT_PATH, 'utf8'))

  it('equals a fresh generation from the token file (run npm run tokens when this fails)', () => {
    expect(css).toBe(generateTokensCss(tokens))
    expect(css.startsWith('/*\n * Generated by scripts/gen-tokens.mjs')).toBe(true)
    expect(css).toContain('Do not edit.')
  })

  it('defines every colour role as a hex variable, light in :root and dark in .dark', () => {
    const light = block(css, ':root')
    const dark = block(css, '.dark')
    for (const role of roleNames) {
      const name = cssVar(tokens, role)
      expect(light, role).toContain(`  ${name}: ${tokens.roles[role].light};`)
      expect(dark, role).toContain(`  ${name}: ${tokens.roles[role].dark};`)
    }
  })

  it('gives every role except the raw ones a channel variable of the same colour', () => {
    const light = block(css, ':root')
    const dark = block(css, '.dark')
    for (const role of roleNames) {
      const name = cssVar(tokens, role)
      if (isRawRole(tokens, role)) {
        expect(light, role).not.toContain(`${name}-rgb`)
        expect(dark, role).not.toContain(`${name}-rgb`)
        continue
      }
      expect(light, role).toContain(`  ${name}-rgb: ${channels(tokens.roles[role].light)};`)
      expect(dark, role).toContain(`  ${name}-rgb: ${channels(tokens.roles[role].dark)};`)
    }
    expect(channels('#0A66D1')).toBe('10 102 209')
  })

  it('keeps the legacy variable names (aliases) for the roles that had one', () => {
    expect(cssVar(tokens, 'bg.page')).toBe('--bg-primary')
    expect(cssVar(tokens, 'text')).toBe('--text-primary')
    expect(cssVar(tokens, 'accent')).toBe('--accent-blue')
    expect(cssVar(tokens, 'border')).toBe('--border-color')
    expect(cssVar(tokens, 'palette.teal')).toBe('--accent-teal')
    expect(cssVar(tokens, 'status.overdue')).toBe('--status-overdue')
  })

  it('defines type, radius and motion variables once, in :root', () => {
    const light = block(css, ':root')
    expect(light).toContain('--type-task-title-size: 14px;')
    expect(light).toContain('--type-task-title-line: 20px;')
    expect(light).toContain('--radius-chip: 9999px;')
    expect(light).toContain('--dur-pop: 360ms;')
    expect(light).toContain('--ease-standard: cubic-bezier(0.2, 0, 0, 1);')
    expect(light).toMatch(/--spring-pop: linear\(0, /)
    expect(block(css, '.dark')).not.toContain('--dur-')
  })
})

describe('index.css', () => {
  const index = lf(readFileSync(resolve(root, 'src/renderer/assets/index.css'), 'utf8'))

  it('imports tokens.css first and does not define a token variable again', () => {
    expect(index.startsWith("@import './tokens.css';")).toBe(true)
    const generated = new Set(
      [...generateTokensCss(tokens).matchAll(/^ {2}(--[a-z0-9-]+):/gm)].map((m) => m[1]),
    )
    const defined = [...index.matchAll(/^ {2}(--[a-z0-9-]+):/gm)].map((m) => m[1])
    // --bg-sidebar is replaced where the window material shows through the sidebar (macOS vibrancy,
    // Windows 11 Mica), light and dark each; the rest must be new names.
    const repeated = defined.filter((name) => generated.has(name))
    expect(repeated).toEqual(['--bg-sidebar', '--bg-sidebar', '--bg-sidebar', '--bg-sidebar'])
  })
})

describe('springs', () => {
  it('start at 0 and end at exactly 1 with 40 to 60 points, in a linear() easing', () => {
    for (const key of ['move', 'moveExpressive', 'pop'] as const) {
      const { spring, ms } = tokens.motion[key]
      const curve = springCurve(spring, ms)
      const m = /^linear\((.+)\)$/.exec(curve)
      expect(m, key).not.toBeNull()
      const points = m![1].split(', ').map(Number)
      expect(points.length, key).toBeGreaterThanOrEqual(40)
      expect(points.length, key).toBeLessThanOrEqual(60)
      expect(points[0]).toBe(0)
      expect(points.at(-1)).toBe(1)
    }
  })

  it('overshoots for the bouncy springs and not for the critically damped one', () => {
    const peak = (key: 'move' | 'moveExpressive' | 'pop') => {
      const { spring, ms } = tokens.motion[key]
      return Math.max(...springCurve(spring, ms).slice(7, -1).split(', ').map(Number))
    }
    expect(peak('pop')).toBeGreaterThan(1.05)
    expect(peak('moveExpressive')).toBeGreaterThan(1.01)
    expect(peak('move')).toBeLessThan(1.01)
    const { spring, ms } = tokens.motion.fade.base
    const fade = springCurve(spring, ms).slice(7, -1).split(', ').map(Number)
    expect(Math.max(...fade)).toBeLessThanOrEqual(1)
  })

  it('follows the closed form of a damped spring', () => {
    // Critically damped (damping ratio 1): x(t) = 1 - e^(-w t) (1 + w t) with w = sqrt(stiffness).
    const w = Math.sqrt(1600)
    expect(springPosition(1, 1600, 0.05)).toBeCloseTo(1 - Math.exp(-w * 0.05) * (1 + w * 0.05), 12)
    expect(springPosition(0.6, 800, 0)).toBe(0)
    expect(springPosition(0.6, 800, 2)).toBeCloseTo(1, 6)
  })

  it('is what the generated variables hold', () => {
    const css = generateTokensCss(tokens)
    for (const [key, name] of [['move', 'move'], ['moveExpressive', 'move-expressive'], ['pop', 'pop']] as const) {
      const { spring, ms } = tokens.motion[key]
      expect(css).toContain(`  --spring-${name}: ${springCurve(spring, ms)};`)
      expect(css).toContain(`  --dur-${name}: ${ms}ms;`)
    }
  })
})

describe('the Tailwind theme', () => {
  const theme = tailwindTheme(tokens)
  const css = lf(readFileSync(OUTPUT_PATH, 'utf8'))

  it('builds colours from channel variables that tokens.css defines', () => {
    for (const [key, value] of Object.entries(theme.colors)) {
      const m = /^rgb\(var\((--[a-z-]+)-rgb\) \/ <alpha-value>\)$/.exec(value) ?? /^var\((--[a-z-]+)\)$/.exec(value)
      expect(m, key).not.toBeNull()
      expect(css, key).toContain(`  ${m![1]}:`)
    }
  })

  it('names colour classes after the roles, keeps bg-sidebar raw and the legacy palette names', () => {
    expect(theme.colors['bg-page']).toBe('rgb(var(--bg-primary-rgb) / <alpha-value>)')
    expect(theme.colors['text-secondary']).toBe('rgb(var(--text-secondary-rgb) / <alpha-value>)')
    expect(theme.colors.border).toBe('rgb(var(--border-color-rgb) / <alpha-value>)')
    expect(theme.colors['accent-fill']).toBe('rgb(var(--accent-fill-rgb) / <alpha-value>)')
    expect(theme.colors['status-overdue']).toBe('rgb(var(--status-overdue-rgb) / <alpha-value>)')
    expect(theme.colors.sidebar).toBe('var(--bg-sidebar)')
    expect(theme.colors['bg-sidebar']).toBeUndefined()
    // Legacy names: accent-blue is the accent role, accent-red to accent-teal the palette.
    expect(theme.colors['accent-blue']).toBe(theme.colors.accent)
    expect(theme.colors['accent-red']).toBe(theme.colors['palette-red'])
    expect(theme.colors['accent-teal']).toBe(theme.colors['palette-teal'])
    expect(Object.keys(theme.colors)).toHaveLength(
      roleNames.length + Object.keys(tokens.css.aliases).filter((role) => tokens.css.aliases[role].startsWith('--accent-')).length,
    )
  })

  it('has type, radius and the tint opacity steps of the contract', () => {
    expect(Object.keys(theme.fontSize)).toEqual(['page-title', 'section', 'group', 'task-title', 'card-title', 'meta', 'chip', 'caption'])
    expect(theme.fontSize.meta).toEqual(['var(--type-meta-size)', { fontWeight: 'var(--type-meta-weight)' }])
    expect(theme.fontSize['task-title'][1]).toMatchObject({ lineHeight: 'var(--type-task-title-line)' })
    expect(Object.keys(theme.borderRadius)).toEqual(['control', 'popover', 'card', 'chip'])
    expect(theme.opacity).toEqual({ 8: '0.08', 12: '0.12' })
  })

  it('makes Tailwind generate opacity classes for the roles and the legacy names', async () => {
    const { default: config } = await import(/* @vite-ignore */ pathToFileURL(resolve(root, 'tailwind.config.ts')).href)
    // Built from parts so this file does not put the class names in front of Tailwind's source scan.
    const cls = (variant: string, utility: string, colour: string, alpha?: number) =>
      `${variant}${utility}-${colour}${alpha === undefined ? '' : `/${alpha}`}`
    const classes = [
      cls('', 'bg', 'accent-blue', 15),
      cls('hover:', 'bg', 'accent-blue', 90),
      cls('', 'bg', 'accent-red', 10),
      cls('placeholder:', 'text', 'text-secondary', 50),
      cls('', 'border', 'border', 50),
      cls('', 'bg', 'status-overdue', 8),
      cls('', 'bg', 'accent-fill'),
      cls('', 'bg', 'sidebar'),
      cls('', 'bg', 'sidebar', 50),
      cls('', 'text', 'meta'),
      cls('', 'rounded', 'card'),
    ]
    const result = await postcss([tailwindcss({ ...config, content: [{ raw: classes.join(' '), extension: 'html' }] })]).process(
      '@tailwind utilities;',
      { from: undefined },
    )
    const out = result.css
    expect(out).toMatch(/\.bg-accent-blue\\\/15 \{\s*background-color: rgb\(var\(--accent-blue-rgb\) \/ 0\.15\)/)
    expect(out).toMatch(/\.hover\\:bg-accent-blue\\\/90:hover \{\s*background-color: rgb\(var\(--accent-blue-rgb\) \/ 0\.9\)/)
    expect(out).toMatch(/\.bg-accent-red\\\/10 \{\s*background-color: rgb\(var\(--accent-red-rgb\) \/ 0\.1\)/)
    expect(out).toMatch(/\.placeholder\\:text-text-secondary\\\/50::placeholder \{\s*color: rgb\(var\(--text-secondary-rgb\) \/ 0\.5\)/)
    expect(out).toMatch(/\.border-border\\\/50 \{\s*border-color: rgb\(var\(--border-color-rgb\) \/ 0\.5\)/)
    expect(out).toMatch(/\.bg-status-overdue\\\/8 \{\s*background-color: rgb\(var\(--status-overdue-rgb\) \/ 0\.08\)/)
    expect(out).toMatch(/\.bg-accent-fill \{[^}]*rgb\(var\(--accent-fill-rgb\) \/ var\(--tw-bg-opacity, 1\)\)/)
    expect(out).toMatch(/\.bg-sidebar \{[^}]*background-color: var\(--bg-sidebar\)/)
    expect(out).not.toContain('bg-sidebar\\/50')
    expect(out).toMatch(/\.text-meta \{\s*font-size: var\(--type-meta-size\);\s*font-weight: var\(--type-meta-weight\)/)
    expect(out).toMatch(/\.rounded-card \{\s*border-radius: var\(--radius-card\)/)
  })
})

describe('the fixture location', () => {
  it('is the shared test-fixtures file', () => {
    expect(FIXTURE_PATH).toBe(resolve(root, 'test-fixtures', 'design-tokens-v1.json'))
  })
})
